name: Run Python job every day

on:
  schedule:
    - cron: '*/10 * * * *'   # UTC时间+8才是北京时间，这是北京时间7：05

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install -r ./requirements.txt && python ./main.py
